### PR TITLE
installation script added

### PR DESCRIPTION
**Pull request by amarjeetkapoor1**

### CODE REVIEW

**Comment by jasvir99** [comment]
That seems a pretty good effort but it's not a complete yet. You have to change STATICFILES_DIRS in settings. Please attach an output of the script and make sure that LH is running properly after you installed it using the script.

**Comment by amarjeetkapoor1** [comment]
STATICFILES_DIRS in setting should be have static relative path. So, no need to change it everytime.

**Comment by mandeeps708** [comment]
Check it by installing on some fresh environment (or system). See if you have it working correctly!

**Comment by amarjeetkapoor1** [comment]
I have installed LibreHatti on my system using that script only but now I am improving it to support exim4 configuration.

**Comment by amarjeetkapoor1** [comment]
Updated and it works correctly. Going to merge after  sometime. If any problem in script is found. Please report by end as soon as possible.

**Pull request merged**
