### PR TITLE
 pdf showing database structure added

### PR DESCRIPTION
**Pull request by amarjeetkapoor1**
To understand database model of LiberHatti  these pdf have been added to show connection between various database table and this line "from librehatti.catalog.models import ModeOfPayment" src/librehatti/bills/models.py has been deleted because of no use of "ModeOfPayment " in that file.

### CODE REVIEW

**Comment by jasvir99** [comment]
I don't think that there any need of such file. If you want to add any image showing relationships between tables, generate a structured image from which one can understand something. Probably, mysql workbench is the tool that can help you. Once I created relational document using it. 

Check attachment.
lh

**Comment by amarjeetkapoor1** [comment]
Is this image representing the current relationship of tables in database?

**Comment by jasvir99** [comment]
No. I created this months before. But you can generate new one too using mysql workbench.

**Comment by amarjeetkapoor1** [comment]
We have created one recently should I add it. I think, we should as a documentation of its database.

**Comment by SatinderpalSingh** [comment]
if(merge request required){
do commit 
}
else{
close request 
}

**Comment by amarjeetkapoor1** [comment]
Any comments or suggestion regarding the future of this pull request.

**Comment by jasvir99** [comment]
Go ahead. Just make sure that it's updated. Whenever you make any changes in DB, update the design file too. I am closing this PR. You should generate new file and send PR again.

**Pull request closed without merging**
